[project]
name = "aitho-seminario"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.4.7",
    "ollama>=0.5.0",
    "pydantic>=2.11.5",
    "ruff>=0.11.12",
]
